### ISSUE TITLE
Question about meaning of phase_occ

### ISSUE THREAD

**Issue by BackMountainDevil** [Traffic-Alpha/LLM-Assisted-Light#1]
phase_occ is used in LLM-Assisted-Light/ConventionalMethods/sotl.py. Is it meaning the length of the cars in the same lane?

**Comment by wmn7** [comment]
Hello,

Thank you for reaching out and for your interest in the LLM-Assisted-Light project. 

In the context of `sotl.py`, the term `phase_occ` stands for "phase occupancy." It is a metric used to calculate the occupancy rate of a given phase at an intersection. Essentially, if phase 1 consists of traffic movements 1 and 5, the occupancy for phase 1 would be the average occupancy of those two movements.

The signal control logic in the script uses `phase_occ` to prioritize phases. The phase with the higher occupancy is given precedence, allowing that phase to pass first in order to optimize traffic flow.

I hope this clarifies your question. If you have any further inquiries or need additional information, please feel free to ask.

Best regards,
